"""
daedalus_gen.py — Data models plus everything that turns them into Daedalus
(.d) code, plain-text dialog exports, and back again (parsing). No Qt here.
"""

import re


def is_hero_speaker(speaker):
    return speaker == "other"

def speaker_display_name(speaker):
    return "Hero" if is_hero_speaker(speaker) else "NPC"


# ── Data models ───────────────────────────────────────────────────────────────
class DialogLine:
    def __init__(self, speaker="self", text=""):
        self.speaker = speaker   # "self" = NPC, "other" = Hero
        self.text = text

class DialogChoice:
    def __init__(self, label="", func_name=""):
        self.label = label
        self.func_name = func_name


class DialogBlock:
    """A dialog scene. Either a top-level C_INFO instance, or a follow-up
    'func void' triggered by a choice in another block (is_followup=True)."""
    def __init__(self):
        self.name = ""; self.description = ""; self.nr = 1
        self.permanent = 0; self.important = 0; self.condition_expr = ""
        self.lines: list[DialogLine] = []
        self.choices: list[DialogChoice] = []
        self.give_xp = ""; self.give_item = ""; self.give_item_count = 1
        self.take_item = ""; self.take_item_count = 1
        self.log_topic = ""; self.log_entry = ""; self.log_status = "LOG_RUNNING"
        self.stop_after = True; self.is_exit = False; self.is_trade = False

        # Follow-up (choice) scenes only:
        self.is_followup = False
        self.func_name = ""          # fixed export identifier, e.g. DIA_Gomez_Reward_Choice1
        self.parent_block = None     # the DialogBlock this is a choice of (runtime link, not exported)


# ── Code generator ────────────────────────────────────────────────────────────
def sanitize(n): return re.sub(r'[^A-Za-z0-9_]', '_', n)

def voice_code(bname, idx, speaker):
    return f"{bname}_{'15' if speaker == 'other' else '10'}_{idx:02d}"

def _log_type(s): return "LOG_MISSION" if ("RUNNING" in s or "SUCCESS" in s) else "LOG_NOTE"

def export_block_name(npc_name, block_name):
    """The exported instance identifier for a top-level scene, e.g. DIA_Gomez_Hello."""
    safe = sanitize(npc_name)
    bn = sanitize(block_name) if block_name else f"DIA_{safe}_Block"
    if not bn.startswith("DIA_"): bn = f"DIA_{safe}_{bn}"
    return bn


def _give_item_lines(b, target="hero"):
    out = []
    if not b.give_item: return out
    if b.give_item_count > 1:
        out.append(f"\tCreateInvItems(self, {b.give_item}, {b.give_item_count});")
    else:
        out.append(f"\tCreateInvItem(self, {b.give_item});")
    out.append(f"\tB_GiveInvItems (self, {target}, {b.give_item}, {b.give_item_count});")
    return out

def _effect_lines(b):
    out = []
    if b.give_xp: out.append(f"\tB_GiveXP({b.give_xp});")
    out += _give_item_lines(b)
    if b.take_item: out.append(f"\tB_GiveInvItems(other, self, {b.take_item}, {b.take_item_count});")
    if b.log_topic:
        out.append(f"\tLog_CreateTopic\t({b.log_topic}, {_log_type(b.log_status)});")
        out.append(f"\tLog_SetTopicStatus\t({b.log_topic}, {b.log_status});")
    if b.log_entry:
        out.append(f'\tB_LogEntry\t({b.log_topic or "LOG_TOPIC"},"{b.log_entry}");')
    return out

def _output_lines(b, bn):
    out = []
    for i, dl in enumerate(b.lines):
        sf = "other" if dl.speaker == "other" else "self"
        st = "self"  if dl.speaker == "other" else "other"
        out.append(f'\tAI_Output ({sf}, {st},"{voice_code(bn, i, dl.speaker)}"); //{dl.text}')
    return out

def _render_followup(b, all_blocks, root_bn):
    """Render one choice follow-up as a `func void` block, then its own
    children (choices made inside this follow-up), recursively."""
    children = [c for c in all_blocks if c.parent_block is b]
    out = [f"func void {b.func_name}()", "{"]
    out += _output_lines(b, b.func_name)
    if b.choices or children:
        out.append(f"\tInfo_ClearChoices\t({b.func_name});")
        for ch in b.choices:
            out.append(f'\tInfo_AddChoice\t({b.func_name},"{ch.label}",{ch.func_name});')
    out += _effect_lines(b)
    if not b.choices and not children:
        out.append(f"\tInfo_ClearChoices\t({root_bn});")
    out += ["};", ""]
    for child in children:
        out += _render_followup(child, all_blocks, root_bn)
    return out


def generate_dia_file(npc_name, npc_id, blocks):
    safe = sanitize(npc_name)
    out = [f"// Dialog file for {npc_name} ({npc_id})",
           "// Generated by Gothic Dialog Generator", ""]

    en = f"DIA_{safe}_EXIT"
    out += ["// " + "="*60, "// \t\t\t\t\tEXIT", "// " + "="*60,
            f"instance {en} (C_INFO)", "{",
            f"\tnpc\t\t\t= {npc_id};", f"\tnr\t\t\t= 999;",
            f"\tcondition\t= {en}_Condition;", f"\tinformation\t= {en}_Info;",
            f"\tpermanent\t= 1;", f"\tdescription = DIALOG_ENDE;", "};", "",
            f"FUNC int {en}_Condition()", "{", f"\treturn 1;", "};", "",
            f"FUNC VOID {en}_Info()", "{", f"\tAI_StopProcessInfos\t(self);", "};", ""]

    top_level = [b for b in blocks if not b.is_exit and not b.is_followup]
    for b in top_level:
        bn = export_block_name(npc_name, b.name)
        out += ["// " + "="*60, f"// \t\t\t{b.description or b.name}", "// " + "="*60,
                f"instance {bn} (C_INFO)", "{",
                f"\tnpc\t\t\t= {npc_id};", f"\tnr\t\t\t= {b.nr};",
                f"\tcondition\t= {bn}_Condition;", f"\tinformation\t= {bn}_Info;",
                f"\tpermanent\t= {b.permanent};"]
        if b.important: out.append(f"\timportant\t= 1;")
        if b.description and not b.important: out.append(f'\tdescription\t= "{b.description}";')
        if b.is_trade: out.append(f"\tTrade\t\t= 1;")
        out += ["};", "", f"FUNC int {bn}_Condition()", "{"]
        if b.condition_expr.strip():
            for cl in b.condition_expr.strip().splitlines(): out.append(f"\t{cl}")
        else:
            out.append("\treturn 1;")
        out += ["};", "", f"FUNC VOID {bn}_Info()", "{"]
        if b.choices: out.append(f"\tInfo_ClearChoices\t({bn});")
        out += _output_lines(b, bn)
        if b.choices:
            for ch in b.choices:
                out.append(f'\tInfo_AddChoice\t({bn},"{ch.label}",{ch.func_name});')
        out += _effect_lines(b)
        if b.stop_after and not b.choices: out.append("\tAI_StopProcessInfos\t(self);")
        out += ["};", ""]

        for f in [c for c in blocks if c.parent_block is b]:
            out += _render_followup(f, blocks, root_bn=bn)

    return "\n".join(out)


def generate_constants_file(npc_name, blocks):
    topics = sorted({b.log_topic for b in blocks if b.log_topic})
    if not topics: return f"// No log constants needed for {npc_name}\n"
    out = [f"// Log constants for {npc_name} dialogs",
           "// Add to Constants.d or a dedicated _CONST.d", "",
           "// ── Log Topic IDs ──────────────────────────────────"]
    for i, t in enumerate(topics, 100): out.append(f"const int {t} = {i};")
    out.append("")
    return "\n".join(out)


def export_plain_dialog(blocks):
    """A simple 'Speaker - line' reference text, scene by scene, in reading
    order (each scene followed immediately by any choice follow-ups it has)."""
    out = []

    def walk(b):
        if b.lines:
            out.append(f"-- {b.name or 'Scene'} --")
            for ln in b.lines:
                out.append(f"{speaker_display_name(ln.speaker)} - {ln.text}")
            out.append("")
        for c in [c for c in blocks if c.parent_block is b]:
            walk(c)

    for b in blocks:
        if b.is_exit or b.is_followup: continue
        walk(b)
    return "\n".join(out).strip() + "\n"


# ── Parser (round-trips files produced by this tool) ───────────────────────────
def _parse_body(seg, bn):
    """Pull the shared pieces (lines, choices, effects) out of one function
    body — used for both top-level Info() bodies and follow-up func bodies."""
    b_lines, b_choices = [], []
    for m in re.finditer(r'AI_Output\s*\((\w+),\s*(\w+),\s*"[^"]*"\);\s*//(.*)', seg):
        sf, txt = m.group(1), m.group(3).strip()
        speaker = "other" if sf == "other" else "self"
        b_lines.append(DialogLine(speaker=speaker, text=txt))

    for m in re.finditer(r'Info_AddChoice\s*\(\s*\w+\s*,\s*"([^"]*)"\s*,\s*(\w+)\s*\);', seg):
        b_choices.append(DialogChoice(label=m.group(1), func_name=m.group(2)))

    give_xp = ""
    xp_m = re.search(r'B_GiveXP\(([^)]*)\);', seg)
    if xp_m: give_xp = xp_m.group(1).strip()

    give_item, give_item_count = "", 1
    gi_m = re.search(r'B_GiveInvItems\s*\(self,\s*\w+,\s*([^,]+),\s*(\d+)\);', seg)
    if gi_m: give_item = gi_m.group(1).strip(); give_item_count = int(gi_m.group(2))

    take_item, take_item_count = "", 1
    ti_m = re.search(r'B_GiveInvItems\s*\(other,\s*self,\s*([^,]+),\s*(\d+)\);', seg)
    if ti_m: take_item = ti_m.group(1).strip(); take_item_count = int(ti_m.group(2))

    log_topic, log_status = "", "LOG_RUNNING"
    status_m = re.search(r'Log_SetTopicStatus\s*\(([^,]+),\s*(\w+)\);', seg)
    if status_m:
        log_topic, log_status = status_m.group(1).strip(), status_m.group(2).strip()
    else:
        topic_m = re.search(r'Log_CreateTopic\s*\(([^,]+),', seg)
        if topic_m: log_topic = topic_m.group(1).strip()

    log_entry = ""
    entry_m = re.search(r'B_LogEntry\s*\([^,]+,\s*"([^"]*)"\);', seg)
    if entry_m: log_entry = entry_m.group(1)

    stop_after = bool(re.search(r'AI_StopProcessInfos\s*\(self\);', seg))

    return dict(lines=b_lines, choices=b_choices, give_xp=give_xp,
                give_item=give_item, give_item_count=give_item_count,
                take_item=take_item, take_item_count=take_item_count,
                log_topic=log_topic, log_status=log_status,
                log_entry=log_entry, stop_after=stop_after)


def _apply_body(b, body):
    b.lines = body["lines"]; b.choices = body["choices"]
    b.give_xp = body["give_xp"]
    b.give_item = body["give_item"]; b.give_item_count = body["give_item_count"]
    b.take_item = body["take_item"]; b.take_item_count = body["take_item_count"]
    b.log_topic = body["log_topic"]; b.log_status = body["log_status"]
    b.log_entry = body["log_entry"]; b.stop_after = body["stop_after"]


def _parse_followups(parent_block, choices, full_text, blocks_out):
    for ch in choices:
        name = ch.func_name
        m = re.search(rf'func void {re.escape(name)}\s*\(\)\s*\{{(.*?)\n\}};', full_text, re.S)
        if not m: continue
        fb = DialogBlock()
        fb.is_followup = True
        fb.name = ch.label or name
        fb.func_name = name
        fb.parent_block = parent_block
        body = _parse_body(m.group(1), name)
        _apply_body(fb, body)
        blocks_out.append(fb)
        if body["choices"]:
            _parse_followups(fb, body["choices"], full_text, blocks_out)


def parse_dia_file(text):
    header_m = re.search(r'//\s*Dialog file for\s+(.*?)\s*\((.*?)\)', text)
    npc_name = header_m.group(1).strip() if header_m else ""
    npc_id   = header_m.group(2).strip() if header_m else ""
    prefix = f"DIA_{sanitize(npc_name)}_"

    blocks = []
    segments = re.split(r'\binstance\s+', text)
    for seg in segments[1:]:
        seg = "instance " + seg
        name_m = re.match(r'instance\s+(\w+)\s*\(C_INFO\)', seg)
        if not name_m:
            continue
        bn = name_m.group(1)
        if bn.endswith("_EXIT"):
            continue  # the EXIT block is regenerated automatically, skip it

        body_m = re.search(r'\{(.*?)\}\s*;', seg, re.S)
        inst_body = body_m.group(1) if body_m else ""

        def field(pat, default=""):
            m = re.search(pat, inst_body)
            return m.group(1).strip() if m else default

        b = DialogBlock()
        b.name = bn[len(prefix):] if bn.startswith(prefix) else bn
        try: b.nr = int(field(r'nr\s*=\s*(\d+)\s*;', "1"))
        except ValueError: b.nr = 1
        perm = field(r'permanent\s*=\s*(\d+)\s*;', "0")
        b.permanent = int(perm) if perm.isdigit() else 0
        b.important = 1 if re.search(r'important\s*=\s*1\s*;', inst_body) else 0
        b.description = field(r'description\s*=\s*"([^"]*)"\s*;', "")
        b.is_trade = bool(re.search(r'Trade\s*=\s*1\s*;', inst_body))

        cond_m = re.search(rf'FUNC int {re.escape(bn)}_Condition\(\)\s*\{{(.*?)\}};\s*FUNC VOID', seg, re.S)
        cond_body = cond_m.group(1).strip() if cond_m else ""
        if cond_body and cond_body != "return 1;":
            b.condition_expr = cond_body

        info_m = re.search(rf'FUNC VOID {re.escape(bn)}_Info\(\)\s*\{{(.*)', seg, re.S)
        info_body = info_m.group(1) if info_m else ""
        cut = info_body.find("\n};")
        if cut != -1: info_body = info_body[:cut]

        body = _parse_body(info_body, bn)
        _apply_body(b, body)
        blocks.append(b)
        if body["choices"]:
            _parse_followups(b, body["choices"], text, blocks)

    # sort top-level scenes by nr, keeping each one's follow-ups clustered
    # immediately after it so the flat list stays in pre-order (parent, then
    # its children, recursively) — that's the order the UI expects to append in.
    clusters, current = [], None
    for blk in blocks:
        if not blk.is_followup:
            current = (blk, [])
            clusters.append(current)
        else:
            current[1].append(blk)
    clusters.sort(key=lambda c: c[0].nr)
    ordered = []
    for top, children in clusters:
        ordered.append(top); ordered.extend(children)
    return npc_name, npc_id, ordered
