// Dialog file for Rezus (MOD_707_Rezus)
// Generated by Gothic Dialog Generator

// ============================================================
// 					EXIT
// ============================================================
instance DIA_Rezus_EXIT (C_INFO)
	npc			= MOD_707_Rezus;
	nr			= 999;
	condition	= DIA_Rezus_EXIT_Condition;
	information	= DIA_Rezus_EXIT_Info;
	permanent	= 1;
	description = DIALOG_ENDE;
};

FUNC int DIA_Rezus_EXIT_Condition()
	return 1;
FUNC VOID DIA_Rezus_EXIT_Info()
	AI_StopProcessInfos	(self);

// ============================================================
// 			Hej!
// ============================================================
instance DIA_Rezus_Hej (C_INFO)
	npc			= MOD_707_Rezus;
	nr			= 1;
	condition	= DIA_Rezus_Hej_Condition;
	information	= DIA_Rezus_Hej_Info;
	permanent	= 0;
	description	= "Hej!";
};

FUNC int DIA_Rezus_Hej_Condition()
	return 1;

FUNC VOID DIA_Rezus_Hej_Info()
	Info_ClearChoices	(DIA_Rezus_Hej);
	AI_Output (other, self,"DIA_Rezus_Hej_15_00"); //Hej!
	AI_Output (self, other,"DIA_Rezus_Hej_10_01"); //Czego chcesz?
	Info_AddChoice	(DIA_Rezus_Hej,"Szukam kogoś kto wie co i jak.",DIA_Rezus_Hej_Szukam_kogo__kto_wie_co_i_jak_);
	Info_AddChoice	(DIA_Rezus_Hej,"Niewazne...",DIA_Rezus_Hej_Niewazne___);
	B_GiveXP(100);
	B_GiveInvItems(self, other, ItMiNugget, 1);
	Log_CreateTopic	(MOD_Rezus, LOG_MISSION);
	Log_SetTopicStatus	(MOD_Rezus, LOG_RUNNING);
	B_LogEntry	(MOD_Rezus,"Hmm..");
