// Dialog file for Rezus (CUS_101_REZUS)
// Generated by Gothic Dialog Generator

// ============================================================
// 					EXIT
// ============================================================
instance DIA_CUS_101_REZUS_EXIT (C_INFO)
{
	npc			= CUS_101_REZUS;
	nr			= 999;
	condition	= DIA_CUS_101_REZUS_EXIT_Condition;
	information	= DIA_CUS_101_REZUS_EXIT_Info;
	permanent	= 1;
	description = DIALOG_ENDE;
};

FUNC int DIA_CUS_101_REZUS_EXIT_Condition()
{
	return 1;
};

FUNC VOID DIA_CUS_101_REZUS_EXIT_Info()
{
	AI_StopProcessInfos	(self);
};

// ============================================================
// 			HELP
// ============================================================
instance DIA_CUS_101_REZUS_HELP (C_INFO)
{
	npc			= CUS_101_REZUS;
	nr			= 1;
	condition	= DIA_CUS_101_REZUS_HELP_Condition;
	information	= DIA_CUS_101_REZUS_HELP_Info;
	permanent	= 0;
};

FUNC int DIA_CUS_101_REZUS_HELP_Condition()
{
	return 1;
};

FUNC VOID DIA_CUS_101_REZUS_HELP_Info()
{
	Info_ClearChoices	(DIA_CUS_101_REZUS_HELP);
	AI_Output (self, other,"DIA_CUS_101_REZUS_HELP_10_00"); //Hej ty! Stój.
	AI_Output (self, other,"DIA_CUS_101_REZUS_HELP_10_01"); //Szukamy kogoś.
	AI_Output (self, other,"DIA_CUS_101_REZUS_HELP_10_02"); //Według naszych informacji, przetrzymywano go tutaj. W twierdzy.
	AI_Output (self, other,"DIA_CUS_101_REZUS_HELP_10_03"); //Dopiero stamtąd wyszedłeś. Na pewno masz jakieś informacje.
	AI_Output (self, other,"DIA_CUS_101_REZUS_HELP_10_04"); //Odpowiedz nam na kilka pytań, a nagrodzimy twoją pomoc.
	Info_AddChoice	(DIA_CUS_101_REZUS_HELP,"",DIA_CUS_101_REZUS_HELP_YES);
	Info_AddChoice	(DIA_CUS_101_REZUS_HELP,"",DIA_CUS_101_REZUS_HELP_NO);
};

func void DIA_CUS_101_REZUS_HELP_YES()
{
	AI_Output (other, self,"DIA_CUS_101_REZUS_HELP_YES_15_00"); //Pytajcie, ale nic nie obiecuję.
	AI_Output (self, other,"DIA_CUS_101_REZUS_HELP_YES_10_01"); //Wystarczy, że powiesz co wiesz.
	Info_ClearChoices	(DIA_CUS_101_REZUS_HELP);
};

func void DIA_CUS_101_REZUS_HELP_NO()
{
	AI_Output (other, self,"DIA_CUS_101_REZUS_HELP_NO_15_00"); //Nie mam nic do powiedzenia.
	AI_Output (self, other,"DIA_CUS_101_REZUS_HELP_NO_10_01"); //Szkoda. Współpraca z nami zwykle się opłaca.
	Info_ClearChoices	(DIA_CUS_101_REZUS_HELP);
};

// ============================================================
// 			QUESTIONS
// ============================================================
instance DIA_CUS_101_REZUS_QUESTIONS (C_INFO)
{
	npc			= CUS_101_REZUS;
	nr			= 2;
	condition	= DIA_CUS_101_REZUS_QUESTIONS_Condition;
	information	= DIA_CUS_101_REZUS_QUESTIONS_Info;
	permanent	= 0;
};

FUNC int DIA_CUS_101_REZUS_QUESTIONS_Condition()
{
	return 1;
};

FUNC VOID DIA_CUS_101_REZUS_QUESTIONS_Info()
{
	AI_Output (other, self,"DIA_CUS_101_REZUS_QUESTIONS_15_00"); //Kogo szukacie?
	AI_Output (self, other,"DIA_CUS_101_REZUS_QUESTIONS_10_01"); //W tym więzieniu przetrzymywano pewnego przestępcę.
	AI_Output (self, other,"DIA_CUS_101_REZUS_QUESTIONS_10_02"); //Ma na imię Persiusz.
	AI_Output (self, other,"DIA_CUS_101_REZUS_QUESTIONS_10_03"); //Czy spotkałeś kogoś o takim imieniu?
	AI_Output (other, self,"DIA_CUS_101_REZUS_QUESTIONS_15_04"); //Nie przypominam sobie.
	AI_Output (self, other,"DIA_CUS_101_REZUS_QUESTIONS_10_05"); //Czy któryś ze strażników zwracał się tak do któregoś z więźniów?
	AI_Output (other, self,"DIA_CUS_101_REZUS_QUESTIONS_15_06"); //Chyba nie.
	AI_Output (self, other,"DIA_CUS_101_REZUS_QUESTIONS_10_07"); //Dobrze. Oto twoja zapłata.
	CreateInvItems(self, GOLD, 5);
	B_GiveInvItems (self, hero, GOLD, 5);
	B_GiveXP(50);
	AI_StopProcessInfos	(self);
};

// ============================================================
// 			WHOAREYOU
// ============================================================
instance DIA_CUS_101_REZUS_WHOAREYOU (C_INFO)
{
	npc			= CUS_101_REZUS;
	nr			= 3;
	condition	= DIA_CUS_101_REZUS_WHOAREYOU_Condition;
	information	= DIA_CUS_101_REZUS_WHOAREYOU_Info;
	permanent	= 0;
};

FUNC int DIA_CUS_101_REZUS_WHOAREYOU_Condition()
{
	return 1;
};

FUNC VOID DIA_CUS_101_REZUS_WHOAREYOU_Info()
{
	AI_Output (other, self,"DIA_CUS_101_REZUS_WHOAREYOU_15_00"); //Kim jesteście?
	AI_Output (self, other,"DIA_CUS_101_REZUS_WHOAREYOU_10_01"); //Jesteśmy wysłannikami Zakonu Sikka.
	AI_Output (self, other,"DIA_CUS_101_REZUS_WHOAREYOU_10_02"); //Nie mogę ci więcej zdradzić. Prowadzimy delikatną sprawę.
	AI_StopProcessInfos	(self);
};
