// Dialog file for Falk (GRD_002_FALK)
// Generated by Gothic Dialog Generator

// ============================================================
// 					EXIT
// ============================================================
instance DIA_Falk_EXIT (C_INFO)
	npc			= GRD_002_FALK;
	nr			= 999;
	condition	= DIA_Falk_EXIT_Condition;
	information	= DIA_Falk_EXIT_Info;
	permanent	= 1;
	description = DIALOG_ENDE;
};

FUNC int DIA_Falk_EXIT_Condition()
	return 1;
FUNC VOID DIA_Falk_EXIT_Info()
	AI_StopProcessInfos	(self);

// ============================================================
// 			INVENTORY
// ============================================================
instance DIA_Falk_INVENTORY (C_INFO)
	npc			= GRD_002_FALK;
	nr			= 1;
	condition	= DIA_Falk_INVENTORY_Condition;
	information	= DIA_Falk_INVENTORY_Info;
	permanent	= 0;
};

FUNC int DIA_Falk_INVENTORY_Condition()
	return 1;

FUNC VOID DIA_Falk_INVENTORY_Info()
	Info_ClearChoices	(DIA_Falk_INVENTORY);
	AI_Output (other, self,"DIA_Falk_INVENTORY_15_00"); //Mam tu odebrać swoje rzeczy.
	AI_Output (self, other,"DIA_Falk_INVENTORY_10_01"); //Czyżby? Jak się nazywasz?
	AI_Output (other, self,"DIA_Falk_INVENTORY_15_02"); //*Gracz podaje swoje imię*
	AI_Output (self, other,"DIA_Falk_INVENTORY_10_03"); //Sprawdźmy...
	AI_Output (self, other,"DIA_Falk_INVENTORY_10_04"); //Tak, jesteś zwolniony z aresztu.
	AI_Output (self, other,"DIA_Falk_INVENTORY_10_05"); //A oto twoje rzeczy.
	AI_Output (self, other,"DIA_Falk_INVENTORY_10_06"); //Czy wszystko się zgadza?
	Info_AddChoice	(DIA_Falk_INVENTORY,"Tak",DIA_Falk_INVENTORY_MINE_Info);
	Info_AddChoice	(DIA_Falk_INVENTORY,"To chyba nie moje...",DIA_Falk_INVENTORY_NOTMINE_Info);
	B_GiveInvItems(self, other, IT_START, 1);
	Log_CreateTopic	(Zwolnienie, LOG_NOTE);
	Log_SetTopicStatus	(Zwolnienie, LOG_NOTE);
	B_LogEntry	(Zwolnienie,"Oddano mi kilka przedmiotów. Ale nie należą do mnie.");

// ============================================================
// 			INVENTORY_MINE
// ============================================================
instance DIA_Falk_INVENTORY_MINE (C_INFO)
	npc			= GRD_002_FALK;
	nr			= 2;
	condition	= DIA_Falk_INVENTORY_MINE_Condition;
	information	= DIA_Falk_INVENTORY_MINE_Info;
	permanent	= 0;
};

FUNC int DIA_Falk_INVENTORY_MINE_Condition()
	return 1;

FUNC VOID DIA_Falk_INVENTORY_MINE_Info()
	AI_Output (other, self,"DIA_Falk_INVENTORY_MINE_15_00"); //Tak, zgadza się.
	AI_Output (self, other,"DIA_Falk_INVENTORY_MINE_10_01"); //Dobrze, w takim razie możesz iść.
	AI_StopProcessInfos	(self);

// ============================================================
// 			INVENTORY_NOTMINE
// ============================================================
instance DIA_Falk_INVENTORY_NOTMINE (C_INFO)
	npc			= GRD_002_FALK;
	nr			= 3;
	condition	= DIA_Falk_INVENTORY_NOTMINE_Condition;
	information	= DIA_Falk_INVENTORY_NOTMINE_Info;
	permanent	= 0;
};

FUNC int DIA_Falk_INVENTORY_NOTMINE_Condition()
	return 1;

FUNC VOID DIA_Falk_INVENTORY_NOTMINE_Info()
	AI_Output (other, self,"DIA_Falk_INVENTORY_NOTMINE_15_00"); //To chyba pomyłka. Te rzeczy nie są moje?
	AI_Output (self, other,"DIA_Falk_INVENTORY_NOTMINE_10_01"); //Nie? Były zapisane pod twoim imieniem.
	AI_Output (self, other,"DIA_Falk_INVENTORY_NOTMINE_10_02"); //To już nie mój problem. Zrób z nimi co chcesz.
	AI_StopProcessInfos	(self);
