// Dialog file for Malcolm (GRD_001_MALCOLM)
// Generated by Gothic Dialog Generator

// ============================================================
// 					EXIT
// ============================================================
instance DIA_Malcolm_EXIT (C_INFO)
	npc			= GRD_001_MALCOLM;
	nr			= 999;
	condition	= DIA_Malcolm_EXIT_Condition;
	information	= DIA_Malcolm_EXIT_Info;
	permanent	= 1;
	description = DIALOG_ENDE;
};

FUNC int DIA_Malcolm_EXIT_Condition()
	return 1;
FUNC VOID DIA_Malcolm_EXIT_Info()
	AI_StopProcessInfos	(self);

// ============================================================
// 			INTRO
// ============================================================
instance DIA_Malcolm_INTRO (C_INFO)
	npc			= GRD_001_MALCOLM;
	nr			= 1;
	condition	= DIA_Malcolm_INTRO_Condition;
	information	= DIA_Malcolm_INTRO_Info;
	permanent	= 0;
};

FUNC int DIA_Malcolm_INTRO_Condition()
	return 1;

FUNC VOID DIA_Malcolm_INTRO_Info()
	AI_Output (self, other,"DIA_Malcolm_INTRO_10_00"); //Więźniu! Koniec odsiadki. Ruszaj się.
	AI_Output (self, other,"DIA_Malcolm_INTRO_10_01"); //Podążaj korytarzem, aż wyjdziesz na dziedziniec. Zamelduj się w wieży strażniczej.
	AI_Output (self, other,"DIA_Malcolm_INTRO_10_02"); //Tam Kapitan Nador odda ci twój dobytek.
	AI_Output (self, other,"DIA_Malcolm_INTRO_10_03"); //No już, zmywaj się!
	Log_CreateTopic	(CH1_INTRO, LOG_MISSION);
	Log_SetTopicStatus	(CH1_INTRO, LOG_RUNNING);
	B_LogEntry	(CH1_INTRO,"Zwolniono mnie z więzienia. Mam się zgłosić w wieży strażniczej po ekwipunek.");
	AI_StopProcessInfos	(self);

// ============================================================
// 			INTRO_WHERE
// ============================================================
instance DIA_Malcolm_INTRO_WHERE (C_INFO)
	npc			= GRD_001_MALCOLM;
	nr			= 2;
	condition	= DIA_Malcolm_INTRO_WHERE_Condition;
	information	= DIA_Malcolm_INTRO_WHERE_Info;
	permanent	= 0;
};

FUNC int DIA_Malcolm_INTRO_WHERE_Condition()
	return 1;

FUNC VOID DIA_Malcolm_INTRO_WHERE_Info()
	AI_Output (other, self,"DIA_Malcolm_INTRO_WHERE_15_00"); //Dlaczego mnie zwolniono?
	AI_Output (self, other,"DIA_Malcolm_INTRO_WHERE_10_01"); //Widocznie odsiedziałeś swój wyrok. Albo ktoś wpłacił kaucję.
	AI_Output (self, other,"DIA_Malcolm_INTRO_WHERE_10_02"); //Jak dla mnie, to możesz tu sobie zostać.
	AI_StopProcessInfos	(self);
