// Dialog file for Malcolm (grd_001_malcolm)
// Generated by Gothic Dialog Generator

// ============================================================
// 					EXIT
// ============================================================
instance DIA_grd_001_malcolm_EXIT (C_INFO)
{
	npc			= grd_001_malcolm;
	nr			= 999;
	condition	= DIA_grd_001_malcolm_EXIT_Condition;
	information	= DIA_grd_001_malcolm_EXIT_Info;
	permanent	= 1;
	description = DIALOG_ENDE;
};

FUNC int DIA_grd_001_malcolm_EXIT_Condition()
{
	return 1;
};

FUNC VOID DIA_grd_001_malcolm_EXIT_Info()
{
	AI_StopProcessInfos	(self);
};

// ============================================================
// 			wakeup
// ============================================================
instance DIA_grd_001_malcolm_wakeup (C_INFO)
{
	npc			= grd_001_malcolm;
	nr			= 1;
	condition	= DIA_grd_001_malcolm_wakeup_Condition;
	information	= DIA_grd_001_malcolm_wakeup_Info;
	permanent	= 0;
};

FUNC int DIA_grd_001_malcolm_wakeup_Condition()
{
	return 1;
};

FUNC VOID DIA_grd_001_malcolm_wakeup_Info()
{
	Info_ClearChoices	(DIA_grd_001_malcolm_wakeup);
	AI_Output (self, other,"DIA_grd_001_malcolm_wakeup_10_00"); //Wstawaj, koniec odsiadki!
	Log_CreateTopic	(Zwolnienie, LOG_MISSION);
	Log_SetTopicStatus	(Zwolnienie, LOG_RUNNING);
	CreateInvItem(self, it_start);
	B_GiveInvItems (self, hero, it_start, 1);
	AI_Output (other, self,"DIA_grd_001_malcolm_wakeup_15_01"); //Co się dzieje?
	AI_Output (self, other,"DIA_grd_001_malcolm_wakeup_10_02"); //Wychodzisz na wolność.
	AI_Output (self, other,"DIA_grd_001_malcolm_wakeup_10_03"); //Za mną.
	Info_AddChoice	(DIA_grd_001_malcolm_wakeup,"Tak jest.",DIA_grd_001_malcolm_wakeup_yessir);
	Info_AddChoice	(DIA_grd_001_malcolm_wakeup,"Nie.",DIA_grd_001_malcolm_wakeup_no);
};

func void DIA_grd_001_malcolm_wakeup_yessir()
{
	AI_Output (other, self,"DIA_grd_001_malcolm_wakeup_yessir_15_00"); //Tak jest.
	Info_ClearChoices	(DIA_grd_001_malcolm_wakeup);
};

func void DIA_grd_001_malcolm_wakeup_no()
{
	AI_Output (other, self,"DIA_grd_001_malcolm_wakeup_no_15_00"); //Nie.
	Info_ClearChoices	(DIA_grd_001_malcolm_wakeup);
};
