// Dialog file for Malcolm (GRD_100_MALCOLM)
// Generated by Gothic Dialog Generator

// ============================================================
// 					EXIT
// ============================================================
instance DIA_GRD_100_MALCOLM_EXIT (C_INFO)
{
	npc			= GRD_100_MALCOLM;
	nr			= 999;
	condition	= DIA_GRD_100_MALCOLM_EXIT_Condition;
	information	= DIA_GRD_100_MALCOLM_EXIT_Info;
	permanent	= 1;
	description = DIALOG_ENDE;
};

FUNC int DIA_GRD_100_MALCOLM_EXIT_Condition()
{
	return 1;
};

FUNC VOID DIA_GRD_100_MALCOLM_EXIT_Info()
{
	AI_StopProcessInfos	(self);
};

// ============================================================
// 			freedom
// ============================================================
instance DIA_GRD_100_MALCOLM_freedom (C_INFO)
{
	npc			= GRD_100_MALCOLM;
	nr			= 1;
	condition	= DIA_GRD_100_MALCOLM_freedom_Condition;
	information	= DIA_GRD_100_MALCOLM_freedom_Info;
	permanent	= 0;
	important	= 1;
};

FUNC int DIA_GRD_100_MALCOLM_freedom_Condition()
{
	return 1;
};

FUNC VOID DIA_GRD_100_MALCOLM_freedom_Info()
{
	AI_Output (self, other,"DIA_GRD_100_MALCOLM_freedom_10_00"); //To twój szczęśliwy dzień.
	AI_Output (self, other,"DIA_GRD_100_MALCOLM_freedom_10_01"); //Wychodzisz na wolność.
	AI_Output (self, other,"DIA_GRD_100_MALCOLM_freedom_10_02"); //No.. Ruszaj się, zanim ktoś zmieni zdanie.
	AI_Output (other, self,"DIA_GRD_100_MALCOLM_freedom_15_03"); //Dlaczego zwalniacie mnie właśnie teraz?
	AI_Output (self, other,"DIA_GRD_100_MALCOLM_freedom_10_04"); //Widocznie komuś na tobie zależy.
	AI_Output (self, other,"DIA_GRD_100_MALCOLM_freedom_10_05"); //A teraz za mną!
	Log_CreateTopic	(FREEDOM, LOG_NOTE);
	Log_SetTopicStatus	(FREEDOM, LOG_NOTE);
	B_LogEntry	(FREEDOM,"Zwolniono mnie z aresztu, ale Strażnik Malcolm nie zdradził mi powodu. Tak czy siak, wychodzę na wolność.");
};

// ============================================================
// 			discharge
// ============================================================
instance DIA_GRD_100_MALCOLM_discharge (C_INFO)
{
	npc			= GRD_100_MALCOLM;
	nr			= 2;
	condition	= DIA_GRD_100_MALCOLM_discharge_Condition;
	information	= DIA_GRD_100_MALCOLM_discharge_Info;
	permanent	= 0;
	important	= 1;
};

FUNC int DIA_GRD_100_MALCOLM_discharge_Condition()
{
	return 1;
};

FUNC VOID DIA_GRD_100_MALCOLM_discharge_Info()
{
	AI_Output (self, other,"DIA_GRD_100_MALCOLM_discharge_10_00"); //Tutaj się rozstajemy.
	AI_Output (self, other,"DIA_GRD_100_MALCOLM_discharge_10_01"); //Tylko się nie rozczulaj. Może jeszcze tu wrócisz!
	AI_Output (self, other,"DIA_GRD_100_MALCOLM_discharge_10_02"); //A teraz idź dalej korytarzem i schodami do góry.
	AI_Output (self, other,"DIA_GRD_100_MALCOLM_discharge_10_03"); //Tam Kapitan Falk cię wypisze i odda ci twoje rzeczy.
	AI_Output (self, other,"DIA_GRD_100_MALCOLM_discharge_10_04"); //Tylko nie próbuj kręcić się po korytarzach, bo zaciągnę cię z powrotem do celi!
	AI_StopProcessInfos	(self);
};

// ============================================================
// 			Dokąd mam iść?
// ============================================================
instance DIA_GRD_100_MALCOLM_where (C_INFO)
{
	npc			= GRD_100_MALCOLM;
	nr			= 3;
	condition	= DIA_GRD_100_MALCOLM_where_Condition;
	information	= DIA_GRD_100_MALCOLM_where_Info;
	permanent	= 0;
	description	= "Dokąd mam iść?";
};

FUNC int DIA_GRD_100_MALCOLM_where_Condition()
{
	return 1;
};

FUNC VOID DIA_GRD_100_MALCOLM_where_Info()
{
	AI_Output (other, self,"DIA_GRD_100_MALCOLM_where_15_00"); //Gdzie dokładnie mam iść?
	AI_Output (self, other,"DIA_GRD_100_MALCOLM_where_10_01"); //Głuchy jesteś?
	AI_Output (self, other,"DIA_GRD_100_MALCOLM_where_10_02"); //Korytarzem do końca i po schodach.
	AI_Output (self, other,"DIA_GRD_100_MALCOLM_where_10_03"); //Patrz przed siebie i z nikim nie rozmawiaj. Jasne?
	AI_StopProcessInfos	(self);
};
