// Dialog file for Malcolm (GRD_100_malcolm)
// Generated by Gothic Dialog Generator

// ============================================================
// 					EXIT
// ============================================================
instance DIA_GRD_100_malcolm_EXIT (C_INFO)
{
	npc			= GRD_100_malcolm;
	nr			= 999;
	condition	= DIA_GRD_100_malcolm_EXIT_Condition;
	information	= DIA_GRD_100_malcolm_EXIT_Info;
	permanent	= 1;
	description = DIALOG_ENDE;
};

FUNC int DIA_GRD_100_malcolm_EXIT_Condition()
{
	return 1;
};

FUNC VOID DIA_GRD_100_malcolm_EXIT_Info()
{
	AI_StopProcessInfos	(self);
};

// ============================================================
// 			FREEDOM
// ============================================================
instance DIA_GRD_100_malcolm_FREEDOM (C_INFO)
{
	npc			= GRD_100_malcolm;
	nr			= 1;
	condition	= DIA_GRD_100_malcolm_FREEDOM_Condition;
	information	= DIA_GRD_100_malcolm_FREEDOM_Info;
	permanent	= 0;
	important	= 1;
};

FUNC int DIA_GRD_100_malcolm_FREEDOM_Condition()
{
	return 1;
};

FUNC VOID DIA_GRD_100_malcolm_FREEDOM_Info()
{
	AI_Output (self, other,"DIA_GRD_100_malcolm_FREEDOM_10_00"); //Więźniu. Jesteś zwolniony z aresztu.
	AI_Output (self, other,"DIA_GRD_100_malcolm_FREEDOM_10_01"); //Chodź za mną.
	AI_StopProcessInfos(self);
	self.aivar[AIV_PARTYMEMBER] = TRUE;
	Npc_ExchangeRoutine(self,"FREEDOM");
};
