// Dialog file for Morel (GOD_100_MOREL)
// Generated by Gothic Dialog Generator

// ============================================================
// 					EXIT
// ============================================================
instance DIA_GOD_100_MOREL_EXIT (C_INFO)
{
	npc			= GOD_100_MOREL;
	nr			= 999;
	condition	= DIA_GOD_100_MOREL_EXIT_Condition;
	information	= DIA_GOD_100_MOREL_EXIT_Info;
	permanent	= 1;
	description = DIALOG_ENDE;
};

FUNC int DIA_GOD_100_MOREL_EXIT_Condition()
{
	return 1;
};

FUNC VOID DIA_GOD_100_MOREL_EXIT_Info()
{
	AI_StopProcessInfos	(self);
};

// ============================================================
// 			whoareyou
// ============================================================
instance DIA_GOD_100_MOREL_whoareyou (C_INFO)
{
	npc			= GOD_100_MOREL;
	nr			= 1;
	condition	= DIA_GOD_100_MOREL_whoareyou_Condition;
	information	= DIA_GOD_100_MOREL_whoareyou_Info;
	permanent	= 0;
};

FUNC int DIA_GOD_100_MOREL_whoareyou_Condition()
{
	return 1;
};

FUNC VOID DIA_GOD_100_MOREL_whoareyou_Info()
{
	Info_ClearChoices	(DIA_GOD_100_MOREL_whoareyou);
	AI_Output (other, self,"DIA_GOD_100_MOREL_whoareyou_15_00"); //Kim jesteś?
	AI_Output (self, other,"DIA_GOD_100_MOREL_whoareyou_10_01"); //Nazywam się Paweł, ale wszyscy mówią na mnie Morel.
	AI_Output (self, other,"DIA_GOD_100_MOREL_whoareyou_10_02"); //Hej. Przynieś mi piwo i trochę ziela. Cały dzień pracowałem na magazynie.
	AI_Output (self, other,"DIA_GOD_100_MOREL_whoareyou_10_03"); //Zapłacę Ci.
	Info_AddChoice	(DIA_GOD_100_MOREL_whoareyou,"Nie mam teraz czasu.",DIA_GOD_100_MOREL_whoareyou_Choice1);
	Info_AddChoice	(DIA_GOD_100_MOREL_whoareyou,"Jasne!",DIA_GOD_100_MOREL_whoareyou_Choice2);
};

func void DIA_GOD_100_MOREL_whoareyou_Choice1()
{
	AI_Output (other, self,"DIA_GOD_100_MOREL_whoareyou_Choice1_15_00"); //Nie mam teraz czasu.
	AI_Output (self, other,"DIA_GOD_100_MOREL_whoareyou_Choice1_10_01"); //Ty draniu. Nie masz litości.
	B_GiveXP(100);
	Info_ClearChoices	(DIA_GOD_100_MOREL_whoareyou);
};

func void DIA_GOD_100_MOREL_whoareyou_Choice2()
{
	AI_Output (other, self,"DIA_GOD_100_MOREL_whoareyou_Choice2_15_00"); //Jasne!
	AI_Output (self, other,"DIA_GOD_100_MOREL_whoareyou_Choice2_10_01"); //Tylko się pośpiesz.
	Log_CreateTopic	(beerandweed, LOG_MISSION);
	Log_SetTopicStatus	(beerandweed, LOG_RUNNING);
	B_LogEntry	(beerandweed,"Niejaki Morel z miasta chce abym przyniósł mu trochę ziela i piwo. Chyba naprawdę tego potrzebuje.");
	Info_ClearChoices	(DIA_GOD_100_MOREL_whoareyou);
};
