// Dialog file for Falk (GRD_102_FALK)
// Generated by Gothic Dialog Generator

// ============================================================
// 					EXIT
// ============================================================
instance DIA_GRD_102_FALK_EXIT (C_INFO)
{
	npc			= GRD_102_FALK;
	nr			= 999;
	condition	= DIA_GRD_102_FALK_EXIT_Condition;
	information	= DIA_GRD_102_FALK_EXIT_Info;
	permanent	= 1;
	description = DIALOG_ENDE;
};

FUNC int DIA_GRD_102_FALK_EXIT_Condition()
{
	return 1;
};

FUNC VOID DIA_GRD_102_FALK_EXIT_Info()
{
	AI_StopProcessInfos	(self);
};

// ============================================================
// 			DISCHARGE
// ============================================================
instance DIA_GRD_102_FALK_DISCHARGE (C_INFO)
{
	npc			= GRD_102_FALK;
	nr			= 1;
	condition	= DIA_GRD_102_FALK_DISCHARGE_Condition;
	information	= DIA_GRD_102_FALK_DISCHARGE_Info;
	permanent	= 0;
};

FUNC int DIA_GRD_102_FALK_DISCHARGE_Condition()
{
	return 1;
};

FUNC VOID DIA_GRD_102_FALK_DISCHARGE_Info()
{
	Info_ClearChoices	(DIA_GRD_102_FALK_DISCHARGE);
	AI_Output (self, other,"DIA_GRD_102_FALK_DISCHARGE_10_00"); //Imię?
	AI_Output (other, self,"DIA_GRD_102_FALK_DISCHARGE_15_01"); //Jestem [Imię].
	AI_Output (self, other,"DIA_GRD_102_FALK_DISCHARGE_10_02"); //Tak, zgadza się.
	AI_Output (self, other,"DIA_GRD_102_FALK_DISCHARGE_10_03"); //Zwalniam cię z aresztu. Nie jesteś już więźniem Korony.
	AI_Output (self, other,"DIA_GRD_102_FALK_DISCHARGE_10_04"); //Oto twój dobytek.
	CreateInvItem(self, ItWr_MysteriousLetter_Mod);
	B_GiveInvItems (self, hero, ItWr_MysteriousLetter_Mod, 1);
	AI_Output (self, other,"DIA_GRD_102_FALK_DISCHARGE_10_05"); //Sprawdź czy wszystko się zgadza. Później nie będę słuchał skarg.
	AI_Output (self, other,"DIA_GRD_102_FALK_DISCHARGE_10_06"); //A teraz znikaj. I postaraj się tu nie wracać.
	Info_AddChoice	(DIA_GRD_102_FALK_DISCHARGE,"Zgadza się.",DIA_GRD_102_FALK_DISCHARGE_MINE);
	Info_AddChoice	(DIA_GRD_102_FALK_DISCHARGE,"To nie moje...",DIA_GRD_102_FALK_DISCHARGE_NOTMINE);
};

func void DIA_GRD_102_FALK_DISCHARGE_MINE()
{
	AI_Output (other, self,"DIA_GRD_102_FALK_DISCHARGE_MINE_15_00"); //Zgadza się.
	AI_Output (self, other,"DIA_GRD_102_FALK_DISCHARGE_MINE_10_01"); //Dobrze. Podpisz tutaj.
	Log_CreateTopic	(FREEDOM, LOG_MISSION);
	Log_SetTopicStatus	(FREEDOM, LOG_RUNNING);
	B_LogEntry	(FREEDOM,"Oddano mi rzeczy które nie są moje. Nie protestowałem. Nikt raczej nie będzie za nimi tęsknił");
	Info_ClearChoices	(DIA_GRD_102_FALK_DISCHARGE);
};

func void DIA_GRD_102_FALK_DISCHARGE_NOTMINE()
{
	AI_Output (other, self,"DIA_GRD_102_FALK_DISCHARGE_NOTMINE_15_00"); //To nie są moje rzeczy.
	AI_Output (self, other,"DIA_GRD_102_FALK_DISCHARGE_NOTMINE_10_01"); //Czyżby?
	AI_Output (self, other,"DIA_GRD_102_FALK_DISCHARGE_NOTMINE_10_02"); //Są zarejestrowane na ciebie. A to jedyne co mnie interesuje.
	AI_Output (self, other,"DIA_GRD_102_FALK_DISCHARGE_NOTMINE_10_03"); //Zrób z nimi co chcesz. Tutaj nikt nie będzie ich szukał.
	AI_Output (self, other,"DIA_GRD_102_FALK_DISCHARGE_NOTMINE_10_04"); //Podpisz tutaj.
	Log_CreateTopic	(FREEDOM, LOG_MISSION);
	Log_SetTopicStatus	(FREEDOM, LOG_RUNNING);
	B_LogEntry	(FREEDOM,"Oddano mi rzeczy które nie są moje. Kapitan Falk nalegał abym je wziął mimo to.");
	Info_ClearChoices	(DIA_GRD_102_FALK_DISCHARGE);
};
